SELECT DISTINCT *
WHERE {
?p rdf:type wp:Pathway .
?p dc:identifier ?i .
?p dc:title ?t .
?p wp:organismName ?n  .
}

SELECT DISTINCT *
WHERE {
?p rdf:type wp:Pathway .
?p dc:title ?t .
?p wp:organismName ?n  .

?c dcterms:isPartOf ?p .
?c rdf:type wp:GeneProduct .
?c rdfs:label ?t1 .
}

SELECT DISTINCT *
WHERE {
?p rdf:type wp:Pathway .
?p dc:title ?t .
?p wp:organismName ?n  .

?c dcterms:isPartOf ?p .
?c rdf:type wp:Metabolite .
?c rdfs:label ?t1 .
}

# main query

SELECT DISTINCT *
WHERE {
?p rdf:type wp:Pathway .
?p dc:identifier ?i .
?p dc:title ?t .
  
?p wp:organismName ?n  .

?c dcterms:isPartOf ?p .
?c rdf:type wp:GeneProduct .
?c rdfs:label ?t1 .

?c dcterms:isPartOf ?p .
?c rdf:type wp:Metabolite .
?c rdfs:label ?t1 .

}
